name: Generate a new Post-Credit Scene Post when a comment is made on the Post-Credit Scene Collection issue

on:
  issue_comment:
    types: [ created ]

jobs:
  new_post_credit_scene_issue:
    name: New Post-Credit Scene Comment
    # Limited to only nwithan8 commenting on the Post-Credit Scene Collection issue
    if: |
      ${{ !github.event.issue.pull_request 
          &&
          github.event.issue.title == 'Post-Credit Scene Collection'
          &&
          github.event.comment.user.login == 'nwithan8'
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

        # Format:
        #   Movie Name
        #   Year
        #   Yes/No
        #   comma-separated list of tags
      - name: Build Post-Credit Scene post
        id: build_post_credit_scene_post
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          python3 make_new_post_credit_scene_post.py "${COMMENT_BODY}"

      - name: Add new file to git
        run: |
          git add .
          git status

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add new Post-Credit Scene post
